<a href="https://colab.research.google.com/github/atul-9/SoftSevaWork/blob/main/Data_Analysis_and_Manipulation_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

In [1]:
import numpy as np

In [2]:
## A 1-D array called zeros having 10 elements and all the elements are set to zero.

zeroarray= np.zeros(10)
zeroarray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#A 1-D array called vowels having the elements ‘a’, ‘e’, ‘i’, ‘o’ and ‘u’.

vowelarray=np.array(['a', 'e', 'i', 'o','u'])
vowelarray

array(['a', 'e', 'i', 'o', 'u'], dtype='<U1')

In [4]:
# A 2-D array called ones having 2 rows and 5 columns and all the elements are set to 1 and dtype as int.

onestwodarray=np.ones(10,dtype=int).reshape(2,5)
onestwodarray

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
#Use nested Python lists to create a 2-D array called myarray1 having 3 rows and 3 columns and store the following data:

list1=[[2.7,-2,-19],[0,3.4,99.9],[10.6,0,13]]
myarray1=np.array(list1)
myarray1

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

In [6]:
# A 2-D array called myarray2 using arange() having 3 rows and 5 columns with start value = 4, step size 4 and dtype as float.

myarray2= np.arange(4,64,4,dtype=float).reshape(3,5)

myarray2

array([[ 4.,  8., 12., 16., 20.],
       [24., 28., 32., 36., 40.],
       [44., 48., 52., 56., 60.]])

In [7]:
# Find the dimensions, shape, size, data type of the items and itemsize of arrays zeros, vowels, ones, myarray1 and myarray2.



#Attribute of zeros array
print("Attribut of zeros Array:")
print("Dimension: ",zeroarray.ndim)
print("Shape: ",zeroarray.shape)
print("Size ",zeroarray.size)
print("Data Type: ",zeroarray.dtype)

#Attribute of Vowels array
print("\nAttribut of Vowels Array:")
print("Dimension: ",vowelarray.ndim)
print("Shape: ",vowelarray.shape)
print("Size ",vowelarray.size)
print("Data Type: ",vowelarray.dtype)

#Attribute of Ones array
print("\nAttribut of Ones Array:")
print("Dimension: ",onestwodarray.ndim)
print("Shape: ",onestwodarray.shape)
print("Size ",onestwodarray.size)
print("Data Type: ",onestwodarray.dtype)

#Attribute of myarray1 array
print("\nAttribut of myarray1 Array:")
print("Dimension: ",myarray1.ndim)
print("Shape: ",myarray1.shape)
print("Size ",myarray1.size)
print("Data Type: ",myarray1.dtype)

#Attribute of myarray2 array
print("\nAttribut of myarray2 Array:")
print("Dimension: ",myarray2.ndim)
print("Shape: ",myarray2.shape)
print("Size ",myarray2.size)
print("Data Type: ",myarray2.dtype)

Attribut of zeros Array:
Dimension:  1
Shape:  (10,)
Size  10
Data Type:  float64

Attribut of Vowels Array:
Dimension:  1
Shape:  (5,)
Size  5
Data Type:  <U1

Attribut of Ones Array:
Dimension:  2
Shape:  (2, 5)
Size  10
Data Type:  int64

Attribut of myarray1 Array:
Dimension:  2
Shape:  (3, 3)
Size  9
Data Type:  float64

Attribut of myarray2 Array:
Dimension:  2
Shape:  (3, 5)
Size  15
Data Type:  float64


In [8]:
# Reshape the array ones to have all the 10 elements in a single row.

onesreshaped=onestwodarray.reshape(10)

onesreshaped

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [9]:
# Display the 2nd and 3rd element of the array vowels.

print("2nd Element of Array vowel: ",vowelarray[1])
print("3rd Element of Array vowel: ",vowelarray[2])


2nd Element of Array vowel:  e
3rd Element of Array vowel:  i


In [10]:
#Display all elements in the 2nd and 3rd row of the array myarray1.

print("All elements of 2nd and 3rd row of myaaray1: ")
print(myarray1[1:3])

All elements of 2nd and 3rd row of myaaray1: 
[[ 0.   3.4 99.9]
 [10.6  0.  13. ]]


In [11]:
# Display the elements in the 1st and 2nd column of the array myarray1.

print("All elements of 1st and 2nd column of myaaray1: ")
print(myarray1[:,0:2])

All elements of 1st and 2nd column of myaaray1: 
[[ 2.7 -2. ]
 [ 0.   3.4]
 [10.6  0. ]]


In [12]:
# Display the elements in the 1st column of the 2nd and 3rd row of the array myarray1.

print("All elements of 1st column of 2nd and 3rd row of myaaray1: ")
print(myarray1[1:3,1])

All elements of 1st column of 2nd and 3rd row of myaaray1: 
[3.4 0. ]


In [14]:
# Reverse the array of vowels.

vowel_reversed=vowelarray[::-1]
print(vowel_reversed)


['u' 'o' 'i' 'e' 'a']


In [15]:
# Divide all elements of array ones by 3.


divarray=onestwodarray/3
print(divarray)


[[0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]]


In [16]:
# Add the arrays myarray1 and myarray2..

addarray= myarray1+ myarray2[:3,:3]
print(addarray)

[[  6.7   6.   -7. ]
 [ 24.   31.4 131.9]
 [ 54.6  48.   65. ]]


In [17]:
# Subtract myarray1 from myarray2 and store the result in a new array.


subarray=myarray2[:3,:3]-myarray1

print(subarray)

[[  1.3  10.   31. ]
 [ 24.   24.6 -67.9]
 [ 33.4  48.   39. ]]


In [18]:
# Multiply myarray1 and myarray2 element-wise.

elemularray= myarray1*myarray2[:3,:3]
print(elemularray)

[[  10.8  -16.  -228. ]
 [   0.    95.2 3196.8]
 [ 466.4    0.   676. ]]


In [19]:
# Do the matrix multiplication of myarray1 and myarray2 and store the result in a new array myarray3.

mularray= np.matmul(myarray1,myarray2)
print(mularray)

[[ -873.2  -946.4 -1019.6 -1092.8 -1166. ]
 [ 4477.2  4890.4  5303.6  5716.8  6130. ]
 [  614.4   708.8   803.2   897.6   992. ]]


In [20]:
# Divide myarray1 by myarray2.

divarray=myarray1/myarray2[:3,:3]
print(divarray)

[[ 0.675      -0.25       -1.58333333]
 [ 0.          0.12142857  3.121875  ]
 [ 0.24090909  0.          0.25      ]]


In [21]:
# Find the cube of all elements of myarray1 and divide the resulting array by 2.

oparray1=(myarray1**3)/2
oparray1


array([[ 9.841500e+00, -4.000000e+00, -3.429500e+03],
       [ 0.000000e+00,  1.965200e+01,  4.985015e+05],
       [ 5.955080e+02,  0.000000e+00,  1.098500e+03]])

In [22]:
# Find the square root of all elements of myarray2 and divide the resulting array by 2.  The result should be rounded to two places of decimals.

oparray2= np.around(np.sqrt(myarray2)/2,2)

oparray2

array([[1.  , 1.41, 1.73, 2.  , 2.24],
       [2.45, 2.65, 2.83, 3.  , 3.16],
       [3.32, 3.46, 3.61, 3.74, 3.87]])

In [23]:
# Find the transpose of ones and myarray2.

onestransponse=np.transpose(onestwodarray)
print("ones Array Transpose: ",onestransponse)

myarray2transpose=np.transpose(myarray2)
myarray2transpose

ones Array Transpose:  [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


array([[ 4., 24., 44.],
       [ 8., 28., 48.],
       [12., 32., 52.],
       [16., 36., 56.],
       [20., 40., 60.]])

In [24]:
#Sort the array vowels in reverse.

vowelsort=np.sort(vowelarray)[::-1]
vowelsort

array(['u', 'o', 'i', 'e', 'a'], dtype='<U1')

In [25]:
# Sort the array myarray1 such that it brings the lowest value of the column in the first row and so on.

sortarray1=np.sort(myarray1,axis=0)
sortarray1

array([[  0. ,  -2. , -19. ],
       [  2.7,   0. ,  13. ],
       [ 10.6,   3.4,  99.9]])

In [26]:
# Use NumPy.split() to split the array myarray2 into 5 arrays column-wise. Store the resulting arrays in myarray2A, myarray2B, myarray2C, myarray2D and myarray2E. Print the arrays myarray2A, myarray2B, myarray2C, myarray2D and myarray2E..


myarray2A, myarray2B, myarray2C, myarray2D, myarray2E=np.split(myarray2,5,1)
print("myarray2A: ",myarray2A)
print("myarray2B: ",myarray2B)
print("myarray2C: ",myarray2C)
print("myarray2D: ",myarray2D)
print("myarray2E: ",myarray2E)

myarray2A:  [[ 4.]
 [24.]
 [44.]]
myarray2B:  [[ 8.]
 [28.]
 [48.]]
myarray2C:  [[12.]
 [32.]
 [52.]]
myarray2D:  [[16.]
 [36.]
 [56.]]
myarray2E:  [[20.]
 [40.]
 [60.]]


In [27]:
#Split the array zeros at array index 2, 5, 7, 8 and store the resulting arrays in zerosA, zerosB, zerosC and zerosD and print them.

zerosA, zerosB, zerosC, zerosD,zerosE=np.split(zeroarray,[2,5,7,8])
print("zerosA: ",zerosA)
print("zerosB: ",zerosB)
print("zerosC: ",zerosC)
print("zerosD: ",zerosD)
print("zerosE: ",zerosE)

zerosA:  [0. 0.]
zerosB:  [0. 0. 0.]
zerosC:  [0. 0.]
zerosD:  [0.]
zerosE:  [0. 0.]


In [28]:
# Concatenate the arrays myarray2A, myarray2B and myarray2C into an array having 3 rows and 3 columns.

concatedarray=np.concatenate((myarray2A, myarray2B,myarray2C),1)
print(concatedarray)

[[ 4.  8. 12.]
 [24. 28. 32.]
 [44. 48. 52.]]


In [29]:
#Create a 2-D array called myarray4 using arange() having 14 rows and 3 columns with start value = -1, step size 0.25 having. Split this array row wise into 3 equal parts and print the result.

myarray4= np.arange(-1,10.25,0.25).reshape(15,3)
myarray4A,myarray4B,myarray4C= np.split(myarray4,3,axis=0)
print(myarray4A)
print(myarray4B)
print(myarray4C)

[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]
[[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]
[[ 6.5   6.75  7.  ]
 [ 7.25  7.5   7.75]
 [ 8.    8.25  8.5 ]
 [ 8.75  9.    9.25]
 [ 9.5   9.75 10.  ]]


In [30]:
# Find the sum of all elements.
np.sum(myarray4)

202.5

In [31]:
# Find the sum of all elements row wise.
np.sum(myarray4,1)

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  , 29.25])

In [32]:
# Find the sum of all elements column wise.

np.sum(myarray4,0)

array([63.75, 67.5 , 71.25])

In [33]:
# Find the max of all elements.

np.max(myarray4)

10.0

In [34]:
# Find the min of all elements in each row

np.min(myarray4,1)

array([-1.  , -0.25,  0.5 ,  1.25,  2.  ,  2.75,  3.5 ,  4.25,  5.  ,
        5.75,  6.5 ,  7.25,  8.  ,  8.75,  9.5 ])

In [35]:
# Find the mean of all elements in each row.

np.mean(myarray4,1)

array([-0.75,  0.  ,  0.75,  1.5 ,  2.25,  3.  ,  3.75,  4.5 ,  5.25,
        6.  ,  6.75,  7.5 ,  8.25,  9.  ,  9.75])

In [36]:
# Find the standard deviation column wise.

np.std(myarray4,0)

array([3.24037035, 3.24037035, 3.24037035])

# **Pandas**

In [37]:
import pandas as pd

In [38]:
# Create a pandas Series S1 of elements [2, 5, 6, 8, 5, -10, 2, -2].

s1=pd.Series([2, 5, 6, 8, 5, -10, 2, -2])
s1


0     2
1     5
2     6
3     8
4     5
5   -10
6     2
7    -2
dtype: int64

In [39]:
# Recreate a pandas Series S1, include the index option and assign an array of strings containing the labels.

s1= pd.Series([2, 5, 6, 8, 5, -10, 2, -2],index=['a','b','c','d','e','f','g','h'])
s1

a     2
b     5
c     6
d     8
e     5
f   -10
g     2
h    -2
dtype: int64

In [40]:
# Display two arrays individually that make up the Series data structure in Pandas using index and values attributes.

index=s1.index
print('Index:',index)

values=s1.values
print("Values: ",values)


Index: Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='object')
Values:  [  2   5   6   8   5 -10   2  -2]


In [41]:
# Select individual elements of a Series S1 by specifying the Key and Label corresponding to the position of the index.

print(s1[2])
print(s1['c'])


6
6


In [42]:
# Select multiple elements of a Series S1 by specifying the Key and Label corresponding to the position of the index using slicing.

print(s1[0:5])

print(s1['a':'e'])


a    2
b    5
c    6
d    8
e    5
dtype: int64
a    2
b    5
c    6
d    8
e    5
dtype: int64


In [43]:
#  Create a Series S2 and S3 from NumPy Arrays and any other Series.

np1=np.array([2,4,1,5,6,8,3])
s2=pd.Series(np1)
print("S2: ",s2)
np2=np.array([5,-1,0-2,-3,5,4,6])
s3=pd.Series(np2)
print('S3: ',s3)


S2:  0    2
1    4
2    1
3    5
4    6
5    8
6    3
dtype: int64
S3:  0    5
1   -1
2   -2
3   -3
4    5
5    4
6    6
dtype: int64


In [44]:
# Select all elements of Series S1 which are less than 8, Series S2 which are greater than 5 and Series S3 which are less than 0.

print("S1 <8: ")
print(s1[s1<8])

print("S2 >5: ")
print(s2[s2>5])

print("S3 <0 ")
print(s3[s3<0])


S1 <8: 
a     2
b     5
c     6
e     5
f   -10
g     2
h    -2
dtype: int64
S2 >5: 
4    6
5    8
dtype: int64
S3 <0 
1   -1
2   -2
3   -3
dtype: int64


In [45]:
# Perform operations using operators such as (+, -, *, and /) on Series S1, S2 and S3,and any three mathematical functions on each Series.


print(s1+2)
print(s1/2)
print(s1*2)
print(s1-2)

print(s2+5)
print(s2-5)
print(s2*5)
print(s2/5)

print(s3+7)
print(s3-7)
print(s3*7)
print(s3/7)

#########################Mathemetical function

print(s1.pow(2))
print(s2.pow(3))
print(s3.pow(4))

print("S1 sum:" ,s1.sum())
print("S2 sum:" ,s2.sum())
print("S3 sum:" ,s3.sum())

print("ABS s1: ")
print(s1.abs())

print("ABS s2: ")
print(s2.abs())

print("ABS s3: ")
print(s3.abs())

a     4
b     7
c     8
d    10
e     7
f    -8
g     4
h     0
dtype: int64
a    1.0
b    2.5
c    3.0
d    4.0
e    2.5
f   -5.0
g    1.0
h   -1.0
dtype: float64
a     4
b    10
c    12
d    16
e    10
f   -20
g     4
h    -4
dtype: int64
a     0
b     3
c     4
d     6
e     3
f   -12
g     0
h    -4
dtype: int64
0     7
1     9
2     6
3    10
4    11
5    13
6     8
dtype: int64
0   -3
1   -1
2   -4
3    0
4    1
5    3
6   -2
dtype: int64
0    10
1    20
2     5
3    25
4    30
5    40
6    15
dtype: int64
0    0.4
1    0.8
2    0.2
3    1.0
4    1.2
5    1.6
6    0.6
dtype: float64
0    12
1     6
2     5
3     4
4    12
5    11
6    13
dtype: int64
0    -2
1    -8
2    -9
3   -10
4    -2
5    -3
6    -1
dtype: int64
0    35
1    -7
2   -14
3   -21
4    35
5    28
6    42
dtype: int64
0    0.714286
1   -0.142857
2   -0.285714
3   -0.428571
4    0.714286
5    0.571429
6    0.857143
dtype: float64
a      4
b     25
c     36
d     64
e     25
f    100
g      4
h      4
dtype: int64

In [46]:
# Select all the values contained in the Series S1, excluding duplicate.

s1.unique()


array([  2,   5,   6,   8, -10,  -2])

In [47]:
# Select all the values contained in the Series S1, excluding duplicates and count the occurrences of each unique value.

s1.value_counts()



 2     2
 5     2
 6     1
 8     1
-10    1
-2     1
dtype: int64

In [48]:
# Demonstrate the use of isin() membership function on each of the Series S1, S2 and S3.


#check which index contains values from [2,4,6,8,10]
print(s1.isin([2,4,6,8,10]))

#check which index contains values from [1,2,3]
print(s2.isin([1,2,3]))

#check which index contains 0

print(s3.isin([0]))


a     True
b    False
c     True
d     True
e    False
f    False
g     True
h    False
dtype: bool
0     True
1    False
2     True
3    False
4    False
5    False
6     True
dtype: bool
0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool


In [49]:
# Create a Series S4 of elements [2, 5, 6, np.NaN, 5, np.NaN, 2, -2] and demonstrate the use of isnull() and notnull() functions on Series S4.


s4=pd.Series([2, 5, 6, np.NaN, 5, np.NaN, 2, -2] )

#use of isnull()
print(s4.isnull())

#use of notnull()
print(s4.notnull())

0    False
1    False
2    False
3     True
4    False
5     True
6    False
7    False
dtype: bool
0     True
1     True
2     True
3    False
4     True
5    False
6     True
7     True
dtype: bool


In [50]:
# Create a Series S5 from a previously defined dictionary and display it.

mydict={'Science':50,'Maths':60,'English':80,'Hindi':85}
s5=pd.Series(mydict)
s5




Science    50
Maths      60
English    80
Hindi      85
dtype: int64

In [51]:
# Read the data stored as a csv file into a pandas DataFrame titanic using read_csv().

frame1=pd.read_csv("https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv")
frame1



PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [52]:
# Display top 5 and bottom 5 rows of the DataFrame titanic.

print("Top 5: ")
print(frame1.head(5))
print("Bottom 5: ")

frame1.tail(5)


Top 5: 
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN      

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [54]:
# Check the column data types of all the columns of DataFrame titanic.

frame1.dtypes


PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [55]:
# Save (store) Titanic dataset (DataFrame) as a spreadsheet (.xlsx) using to_excel().

frame1.to_excel('data1.xlsx')


In [56]:
# Display the technical summary of a DataFrame titanic.

frame1.info()



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [57]:
# Select a single column of a DataFrame titanic and also check the type() and shape of that column

id= frame1['PassengerId']
id.dtype
id.shape


(891,)

In [58]:
# Select multiple columns of a DataFrame titanic and also check the type() and shape of those columns.

name_age=frame1[['Name','Age']]

print("Data Type: ",name_age.dtypes)
print(type(name_age))
name_age.shape



Data Type:  Name     object
Age     float64
dtype: object
<class 'pandas.core.frame.DataFrame'>


(891, 2)

In [59]:
# Select all the passengers from the titanic DataFrame who are not older than than 50 years.

below50=frame1[frame1["Age"]<50]
below50


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[640 rows x 12 columns]

In [60]:
# Select all titanic passengers from cabin class 1 and 3.

cabin1n3=frame1[frame1['Pclass'].isin([1,3])]
cabin1n3


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[707 rows x 12 columns]

In [61]:
# Select all titanic passengers data for which the age is known using notna() function.

knownage=frame1[frame1['Age'].notna()]
knownage



PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[714 rows x 12 columns]

In [62]:
# Select the names of the titanic passengers not older than 50 years.

namelist=frame1.loc[frame1["Age"]<50,'Name']
namelist


0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
885                 Rice, Mrs. William (Margaret Norton)
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 640, dtype: object

In [63]:
# Select rows 25 till 37 and columns 2 to 6 from a titanic DataFrame.

datasubset=frame1.iloc[25:37,2:6]
datasubset


Pclass                                               Name     Sex   Age
25       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.0
26       3                            Emir, Mr. Farred Chehab    male   NaN
27       1                     Fortune, Mr. Charles Alexander    male  19.0
28       3                      O'Dwyer, Miss. Ellen "Nellie"  female   NaN
29       3                                Todoroff, Mr. Lalio    male   NaN
30       1                           Uruchurtu, Don. Manuel E    male  40.0
31       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female   NaN
32       3                           Glynn, Miss. Mary Agatha  female   NaN
33       2                              Wheadon, Mr. Edward H    male  66.0
34       1                            Meyer, Mr. Edgar Joseph    male  28.0
35       1                     Holverson, Mr. Alexander Oskar    male  42.0
36       3                                   Mamee, Mr. Hanna    male   NaN

In [64]:
# Display the average age of the titanic passengers.

frame1['Age'].mean()


29.69911764705882

In [65]:
# Display median age and ticket fare price of the titanic passengers.

print("Median Age: ",frame1["Age"].median())
print("Median Ticket Fare Price: ",frame1['Fare'].median())


Median Age:  28.0
Median Ticket Fare Price:  14.4542


In [66]:
# Demonstrate the use of describe() on Age and Fare columns of the titanic DataFrame.

print(frame1[["Age","Fare"]].describe())



              Age        Fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200


In [67]:
# Display the average age for male versus female titanic passengers.

frame1[['Age','Sex']].groupby("Sex").mean()


Age
Sex              
female  27.915709
male    30.726645

In [68]:
# Display the mean ticket fare price for each of the sex and cabin class combinations of titanic DataFrame.
frame1[["Fare",'Sex','Pclass']].groupby(['Sex','Pclass']).mean()


Fare
Sex    Pclass            
female 1       106.125798
       2        21.970121
       3        16.118810
male   1        67.226127
       2        19.741782
       3        12.661633

In [69]:
# Display the number of passengers in each of the cabin classes of titanic DataFrame

frame1["Pclass"].value_counts()


3    491
1    216
2    184
Name: Pclass, dtype: int64

In [70]:
# Sort the titanic data according to the age of the passengers.

frame1.sort_values(by='Age')



PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander   
755          756         1       2                 Hamalainen, Master. Viljo   
644          645         1       3                    Baclini, Miss. Eugenie   
469          470         1       3             Baclini, Miss. Helene Barbara   
78            79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
859          860         0       3                          Razi, Mr. Raihed   
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
868          869         0       3               van Melkebeke, Mr. Philemon   
878          879         0       3                        Laleff, Mr. Kristo   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
803    male  0.42      0      1        2625   8.5167   NaN        C  
755    male  0.67      1      1      250649  14.5000   NaN        S  
644  female  0.75      2      1        2666  19.2583   NaN        C  
469  female  0.75      2      1        2666  19.2583   NaN        C  
78     male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
859    male   NaN      0      0        2629   7.2292   NaN        C  
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
868    male   NaN      0      0      345777   9.5000   NaN        S  
878    male   NaN      0      0      349217   7.8958   NaN        S  
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [71]:
# Sort the titanic data according to the cabin class and age in descending order.

frame1.sort_values(by=['Pclass','Age'],ascending=False)


PassengerId  Survived  Pclass  \
851          852         0       3   
116          117         0       3   
280          281         0       3   
483          484         1       3   
326          327         0       3   
..           ...       ...     ...   
766          767         0       1   
793          794         0       1   
815          816         0       1   
839          840         1       1   
849          850         1       1   

                                             Name     Sex   Age  SibSp  Parch  \
851                           Svensson, Mr. Johan    male  74.0      0      0   
116                          Connors, Mr. Patrick    male  70.5      0      0   
280                              Duane, Mr. Frank    male  65.0      0      0   
483                        Turkula, Mrs. (Hedwig)  female  63.0      0      0   
326                     Nysveen, Mr. Johan Hansen    male  61.0      0      0   
..                                            ...     ...   ...    ...    ...   
766                     Brewe, Dr. Arthur Jackson    male   NaN      0      0   
793                      Hoyt, Mr. William Fisher    male   NaN      0      0   
815                              Fry, Mr. Richard    male   NaN      0      0   
839                          Marechal, Mr. Pierre    male   NaN      0      0   
849  Goldenberg, Mrs. Samuel L (Edwiga Grabowska)  female   NaN      1      0   

       Ticket     Fare Cabin Embarked  
851    347060   7.7750   NaN        S  
116    370369   7.7500   NaN        Q  
280    336439   7.7500   NaN        Q  
483      4134   9.5875   NaN        S  
326    345364   6.2375   NaN        S  
..        ...      ...   ...      ...  
766    112379  39.6000   NaN        C  
793  PC 17600  30.6958   NaN        C  
815    112058   0.0000  B102        S  
839     11774  29.7000   C47        C  
849     17453  89.1042   C92        C  

[891 rows x 12 columns]